const PAGE_QUERY_PARAM = 'page'
const OFFSET_QUERY_PARAM = 'offset'
const MAX_PAGES = 10
const AMOUNT_ITEMS_BY_PAGE = 100
const MAX_ITEMS_AMOUNT = MAX_PAGES * AMOUNT_ITEMS_BY_PAGE

exports.PAGE_QUERY_PARAM = PAGE_QUERY_PARAM
exports.OFFSET_QUERY_PARAM = OFFSET_QUERY_PARAM
exports.MAX_PAGES = MAX_PAGES
exports.AMOUNT_ITEMS_BY_PAGE = AMOUNT_ITEMS_BY_PAGE
exports.MAX_ITEMS_AMOUNT = MAX_ITEMS_AMOUNT